rule_files:

  - "postgresql.yml"

scrape_configs:

  - job_name: 'postgres-exporter'
    metrics_path: '/metrics'
    honor_labels: true
    scrape_interval: 300s
    scrape_timeout: 60s
    static_configs:
      - targets: ['postgres-exporter-pgserver94:9187','postgres-exporter-pgserver92:9187']
